version: 3

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate proto files"
    cmds:
      - protoc -I ./protos/proto ./protos/proto/protocol/*.proto --go_out=./protos/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/proto ./protos/proto/auth/*.proto --go_out=./protos/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/proto ./protos/proto/user/*.proto --go_out=./protos/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/proto ./protos/proto/chat/*.proto --go_out=./protos/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/proto ./protos/proto/frontend/*.proto --go_out=./protos/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/ --go-grpc_opt=paths=source_relative
  build-server:
    aliases:
      - build
    desc: "Build server bins"
    cmds:
      - go build -o ./bin/auth.exe ./server/cmd/auth
      - go build -o ./bin/user.exe ./server/cmd/user
      - go build -o ./bin/chat.exe ./server/cmd/chat
      - go build -o ./bin/frontend.exe ./server/cmd/frontend
  build-cli:
    desc: "Build cli bins"
    cmds:
      - go build -o ./bin/cli.exe ./server/cmd/cli
  run-server:
    aliases:
      - run
    desc: "Run server bins"
    cmds:
      - Powershell.exe start ./bin/auth.exe --config="./server/config/local.yaml"
      - Powershell.exe start ./bin/user.exe --config="./server/config/local.yaml"
      - Powershell.exe start ./bin/chat.exe --config="./server/config/local.yaml"
      - Powershell.exe start ./bin/frontend.exe --config="./server/config/local.yaml"
  run-cli:
    desc: "Run cli"
    cmd: Powershell.exe start ./bin/cli.exe