version: 3

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate proto files"
    cmds:
      - protoc -I ./protos/proto ./protos/proto/protocol/*.proto --go_out=./protos/gen/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/ --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/proto ./protos/proto/auth/*.proto --go_out=./protos/gen/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/ --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/proto ./protos/proto/user/*.proto --go_out=./protos/gen/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/ --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/proto ./protos/proto/chat/*.proto --go_out=./protos/gen/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/ --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/proto ./protos/proto/frontend/*.proto --go_out=./protos/gen/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/ --go-grpc_opt=paths=source_relative
  test:
    desc: "Run server tests"
    cmds:
      - go test ./server/...
  build-server-image:
    aliases:
      - build
    desc: "Build server images"
    cmds:
      - docker-compose -f ./deploy/docker-compose.yml build
  run-server:
    aliases:
      - run
    desc: "Run server"
    cmds:
      - docker-compose -f ./deploy/docker-compose.yml up -d
  build-cli:
    desc: "Build cli bins"
    cmds:
      - go build -o ./bin/cli.exe ./server/cmd/cli
  run-cli:
    desc: "Run cli"
    cmd: Powershell.exe start ./bin/cli.exe
