env: "local"
log_level: "debug"
services:
  auth:
    grpc:
      port: 20202
      timeout: 10h
    storage:
      timeout: 1m
      connect_uri: "mongodb://mongo-node1,mongo-node2,mongo-node3/?replicaSet=rs0"
    token_ttl: 1h
  user:
    grpc:
      port: 20202
      timeout: 10h
    storage:
      timeout: 1m
      connect_uri: "mongodb://mongo-node1,mongo-node2,mongo-node3/?replicaSet=rs0"
  chat:
    grpc:
      port: 20202
      timeout: 10h
    chat_storage:
      timeout: 1m
      connect_uri: "mongodb://mongo-node1,mongo-node2,mongo-node3/?replicaSet=rs0"
    message_storage:
      keyspace: "db_message"
      hosts:
        - scylla-node1
        - scylla-node2
        - scylla-node3
  frontend:
    grpc:
      port: 20202
      timeout: 10h
    ws_port: 20203
    ws_base_path: "/ws"
    send_buff_size: 128
    read_buff_size: 4096
    write_buff_size: 4096
    hs_timeout: 30s
    msg_limit: 4096
    write_wait: 5s
    pong_wait: 5s
clients:
  auth:
    address: "auth:20202"
    timeout: 1h
    retries_count: 3
  user:
    address: "user:20202"
    timeout: 1h
    retries_count: 3
  chat:
    address: "chat:20202"
    timeout: 1h
    retries_count: 3
  frontend:
    address: "frontend:20202"
    timeout: 1h
    retries_count: 3