// Code generated by mockery v2.42.3. DO NOT EDIT.

package mock_user

import (
	context "context"

	model "github.com/dvid-messanger/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserSaver is an autogenerated mock type for the UserSaver type
type MockUserSaver struct {
	mock.Mock
}

type MockUserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSaver) EXPECT() *MockUserSaver_Expecter {
	return &MockUserSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, email, bio
func (_m *MockUserSaver) Save(ctx context.Context, email string, bio string) (model.User, error) {
	ret := _m.Called(ctx, email, bio)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.User, error)); ok {
		return rf(ctx, email, bio)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.User); ok {
		r0 = rf(ctx, email, bio)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, bio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - bio string
func (_e *MockUserSaver_Expecter) Save(ctx interface{}, email interface{}, bio interface{}) *MockUserSaver_Save_Call {
	return &MockUserSaver_Save_Call{Call: _e.mock.On("Save", ctx, email, bio)}
}

func (_c *MockUserSaver_Save_Call) Run(run func(ctx context.Context, email string, bio string)) *MockUserSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserSaver_Save_Call) Return(_a0 model.User, _a1 error) *MockUserSaver_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserSaver_Save_Call) RunAndReturn(run func(context.Context, string, string) (model.User, error)) *MockUserSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserSaver creates a new instance of MockUserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSaver {
	mock := &MockUserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
