services:
  user:
    container_name: user-service
    image: user
    build:
      context: ..
      dockerfile: ./deploy/apps/user/Dockerfile
    depends_on:
      - mongosetup
    networks:
      web:

  auth:
    container_name: auth-service
    image: auth
    build:
      context: ..
      dockerfile: ./deploy/apps/auth/Dockerfile
    depends_on:
      - mongosetup
    networks:
      web:

  chat:
    container_name: chat-service
    image: chat
    build:
      context: ..
      dockerfile: ./deploy/apps/chat/Dockerfile
    depends_on:
      - mongosetup
      - scylla-node1
      - scylla-node2
      - scylla-node3
    networks:
      web:

  frontend:
    container_name: frontend-service
    image: frontend
    build:
      context: ..
      dockerfile: ./deploy/apps/frontend/Dockerfile
    ports:
      - 20203:20203
    depends_on:
      - user
      - auth
      - chat
    networks:
      web:

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.2.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:5.2.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:5.2.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

  mongo-node1:
    container_name: mongo-node1
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip", "localhost,mongo-node1"]
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    networks:
      web:

  mongo-node2:
    container_name: mongo-node2
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip", "localhost,mongo-node2"]
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
    networks:
      web:

  mongo-node3:
    container_name: mongo-node3
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip", "localhost,mongo-node3"]
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
    networks:
      web:

  mongosetup:
    image: mongo:7.0
    depends_on:
      - mongo-node1
      - mongo-node2
      - mongo-node3
    volumes:
      - ./db:/db
    restart: "no"
    entrypoint: [ "bash", "/db/mongo_setup.sh" ]
    networks:
      web:


networks:
  web:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config: