// Code generated by mockery v2.42.3. DO NOT EDIT.

package mock_chat

import (
	context "context"

	model "github.com/dvid-messanger/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageSaver is an autogenerated mock type for the MessageSaver type
type MockMessageSaver struct {
	mock.Mock
}

type MockMessageSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageSaver) EXPECT() *MockMessageSaver_Expecter {
	return &MockMessageSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, cid, from, text
func (_m *MockMessageSaver) Save(ctx context.Context, cid []byte, from []byte, text string) (model.ChatMessage, error) {
	ret := _m.Called(ctx, cid, from, text)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 model.ChatMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, string) (model.ChatMessage, error)); ok {
		return rf(ctx, cid, from, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, string) model.ChatMessage); ok {
		r0 = rf(ctx, cid, from, text)
	} else {
		r0 = ret.Get(0).(model.ChatMessage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, []byte, string) error); ok {
		r1 = rf(ctx, cid, from, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMessageSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - cid []byte
//   - from []byte
//   - text string
func (_e *MockMessageSaver_Expecter) Save(ctx interface{}, cid interface{}, from interface{}, text interface{}) *MockMessageSaver_Save_Call {
	return &MockMessageSaver_Save_Call{Call: _e.mock.On("Save", ctx, cid, from, text)}
}

func (_c *MockMessageSaver_Save_Call) Run(run func(ctx context.Context, cid []byte, from []byte, text string)) *MockMessageSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockMessageSaver_Save_Call) Return(_a0 model.ChatMessage, _a1 error) *MockMessageSaver_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageSaver_Save_Call) RunAndReturn(run func(context.Context, []byte, []byte, string) (model.ChatMessage, error)) *MockMessageSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageSaver creates a new instance of MockMessageSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSaver {
	mock := &MockMessageSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
