// Code generated by mockery v2.42.3. DO NOT EDIT.

package mock_chat

import (
	context "context"

	model "github.com/dvid-messanger/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserChatProvider is an autogenerated mock type for the UserChatProvider type
type MockUserChatProvider struct {
	mock.Mock
}

type MockUserChatProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserChatProvider) EXPECT() *MockUserChatProvider_Expecter {
	return &MockUserChatProvider_Expecter{mock: &_m.Mock}
}

// UserChats provides a mock function with given fields: ctx, uid
func (_m *MockUserChatProvider) UserChats(ctx context.Context, uid []byte) ([]model.Chat, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for UserChats")
	}

	var r0 []model.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ([]model.Chat, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []model.Chat); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserChatProvider_UserChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserChats'
type MockUserChatProvider_UserChats_Call struct {
	*mock.Call
}

// UserChats is a helper method to define mock.On call
//   - ctx context.Context
//   - uid []byte
func (_e *MockUserChatProvider_Expecter) UserChats(ctx interface{}, uid interface{}) *MockUserChatProvider_UserChats_Call {
	return &MockUserChatProvider_UserChats_Call{Call: _e.mock.On("UserChats", ctx, uid)}
}

func (_c *MockUserChatProvider_UserChats_Call) Run(run func(ctx context.Context, uid []byte)) *MockUserChatProvider_UserChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockUserChatProvider_UserChats_Call) Return(_a0 []model.Chat, _a1 error) *MockUserChatProvider_UserChats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserChatProvider_UserChats_Call) RunAndReturn(run func(context.Context, []byte) ([]model.Chat, error)) *MockUserChatProvider_UserChats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserChatProvider creates a new instance of MockUserChatProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserChatProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserChatProvider {
	mock := &MockUserChatProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
