// Code generated by mockery v2.42.3. DO NOT EDIT.

package mock_auth

import (
	context "context"

	model "github.com/dvid-messanger/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// User provides a mock function with given fields: ctx, email
func (_m *MockUserProvider) User(ctx context.Context, email string) (model.UserCredentials, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 model.UserCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.UserCredentials, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.UserCredentials); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(model.UserCredentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProvider_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockUserProvider_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserProvider_Expecter) User(ctx interface{}, email interface{}) *MockUserProvider_User_Call {
	return &MockUserProvider_User_Call{Call: _e.mock.On("User", ctx, email)}
}

func (_c *MockUserProvider_User_Call) Run(run func(ctx context.Context, email string)) *MockUserProvider_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserProvider_User_Call) Return(_a0 model.UserCredentials, _a1 error) *MockUserProvider_User_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProvider_User_Call) RunAndReturn(run func(context.Context, string) (model.UserCredentials, error)) *MockUserProvider_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
